#开发环境配置
server:
  port: 8080
#  context-path: /api
logging:
  level:
    root: info
    com.lyl: debug
  file:
    name: logs/debug.log

#local database
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book?serverTimezone=UTC
    username: root
    password: lyl961008
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


#loading static resources
# 应该以什么样的路径来访问静态资源,这表示只有静态资源的访问路径为/static/ 时才会处理(如http://localhost:8080/static/css/base.css)
spring.mvc.static-path-pattern: /static/**
